Update/enc
CybercentreCanada/assemblyline-service-overpower pull request #111
Opened 2023-04-20 20:05 UTC by cccs-kevin

2023-04-20 20:23 UTC, cccs-jh approved these changes

2023-04-21 11:46 UTC, gdesmar requested changes

2023-04-21 11:46 UTC, gdesmar commented on tools/PSDecode.psm1
> +    $encoded_command_pattern = [regex]"(?i)-(?:encodedcommand|enc)\s+['`"]([a-zA-Z0-9+/]+=?=?)['`"]"
The -EncodedCommand can also be written ```powershell /encodedco ZQBjAGgAbwAgAGIAZQBlAA==```, and every variation of letter removed from the word "EncodedCommand". You also don't need the quotes around the base64. I believe this Regex will be able to cover more cases:
https://github.com/CybercentreCanada/Multidecoder/blob/main/multidecoder/analyzers/shell.py#L14

2023-04-21 13:01 UTC, gdesmar approved these changes

2023-04-21 13:02 UTC, merged